//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdiAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckIn
    {
        public int CheckInID { get; set; }
        public Nullable<int> ScheduleID { get; set; }
        public System.DateTime CheckInTime { get; set; }
        public string AdherenceStatus { get; set; }
        public string SideEffects { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual MedicationSchedule MedicationSchedule { get; set; }
    }
}
