//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdiAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor_Patient
    {
        public int DoctorPatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual User User { get; set; }
    }
}
