//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MdiAppProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int GoalID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string GoalType { get; set; }
        public int TargetValue { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual User User { get; set; }
    }
}
